### ISSUE TITLE
Hang out with the Mattermost integrations community? 

### ISSUE THREAD

**Issue by it33** [jonathanwiesel/node-mattermost#2]
Hi @jonathanwiesel, 

Thanks again for creating node-mattermost and matterqus!

Just curious, would you be interested in hanging out with us in our [Integrations and Apps channel](https://pre-release.mattermost.com/core/channels/integrations)? 

I wasn't sure if you were on our nightly builds server yet--if not, would love for you to join us :) 

I'm it33 on there,

**Comment by jonathanwiesel** [comment]
Finally joined, after all this time 😉
